version: "2"
services:
  gateway:
      # should use env file / maybe ovewrite?
      # should use extend file eg gateway.yml
      # we can extend with network later
      # backups migration and stuff can be done later?
    build: .
    #command: npm start
    links:
      - postgres
    volumes:
      - .:/app
      - /app
    # ports:
    #  - 3000:3000
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
