version: "2"
services:
  gateway:
    build: .
    command: node_modules/.bin/nodemon index.js
    volumes:
      - .:/app
    ports:
      - 3000:3000
    links:
      - postgres
    environment:
      - POSTGRES_PORT_5432_TCP_ADDR=postgres
      - POSTGRES_PASSWORD=${PASSWORD}
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
